### ISSUE TITLE
Lab2 review

### ISSUE THREAD

**Issue by H30H** [ResQkiT/MEPHI_CODEBASE#6]
- [x]  Нужны 2 версии методов, с const и без, прям как ты сделал в `SharedPtr` + обработать ситуацию с `ptr == nullptr`, когда идёт обращение к `nullptr`
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/smart_pointers/UniquePtr.hpp#L33-L36

- [x] Тут тоже 2 версии метода const и не const 
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/smart_pointers/SharedPtr.hpp#L119-L121

- [x] Вот этот метод удали, тк это не безопасно. Благодаря ему можно изменить счётчики и сломать умный указатель
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/smart_pointers/SharedPtr.hpp#L144

- [x] Не проверяешь на `ref_counter != nullptr`, хотя потенциально они могут ему равняться
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/smart_pointers/WeakPtr.hpp#L17-L23

- [x] В классе `WeakPtr` забыл сделать `WeakPtr& operator=(WeakPtr&& other)`

- [x] Переделай копирование листа, сейчас оно имеет сложность $O(n^2)$, из-за сложности метода `push_back()` $O(n)$, хотя само копирование можно сделать за $O(n)$. Решения этой проблемы 2: переделать `push_back()`, чтобы его сложность была $O(1)$, или сделать копирование без `push_back()`. И то же для `get_sublist()`
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/LinkedList.hpp#L22-L34
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/LinkedList.hpp#L101-L108

- [x] Вот тут ты создаёшь `SharedPtr` на `LinkedList`, потом его полностью копируешь в `UniquePtr` в конструкторе класса `LinkedListSequence`, а затем удаляешь исходный `SharedPtr`. Зачем так сложно? Попробуй лучше вернуть из метода `get_sublist()` сразу `UniquePtr` и от него создай экземпляр класса `LinkedListSequence`, не вызывая при этом лишних копирований
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/LinkedListSequence.hpp#L34-L43

- [x] `size_t` это беззнаковый очень большой int, и он не может быть меньше нуля. Есть ещё несколько мест, где ты проверяешь подобное. Убери пж
https://github.com/ResQkiT/C_MEPHI/blob/0453dffb7e321609dc1714a6ddd43034e23b0e9e/GRAD3/Lab1/LinkedListSequence.hpp#L34-L35

**Comment by ResQkiT** [comment]
Изменения внесены
